version: '3.9'
services:
  api:
    build: ./api
    ports:
      - "90:5000"
    volumes:
      - ./api:/app
    environment:
      FLASK_ENV: development
  app:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/user/src/app
    depends_on:
      - api